### ISSUE TITLE
Need to create system/fluid and system/solid in cz_grid.py example 

### ISSUE THREAD

**Issue by jmozmoz** [nemocrys/nemoblock#1]
cz_grid.py stops with error messages, if the subfolders system/solid and system/fluid have not been created by hand:

```
Traceback (most recent call last):
  File "cz_grid.py", line 177, in <module>
    os.rename("./system/blockMeshDict", "./system/fluid/blockMeshDict")
FileNotFoundError: [Errno 2] No such file or directory: './system/blockMeshDict' -> './system/fluid/blockMeshDict'
```

```
Traceback (most recent call last):
  File "cz_grid.py", line 218, in <module>
    os.rename("./system/blockMeshDict", "./system/solid/blockMeshDict")
FileNotFoundError: [Errno 2] No such file or directory: './system/blockMeshDict' -> './system/solid/blockMeshDict'
```

**Comment by arvedes** [comment]
Thanks for reporting this, I'll check if there are similar issues in the other examples. Please let me know if you find other problems or have any questions!
